// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sum struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sum) Reset()         { *m = Sum{} }
func (m *Sum) String() string { return proto.CompactTextString(m) }
func (*Sum) ProtoMessage()    {}
func (*Sum) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *Sum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sum.Unmarshal(m, b)
}
func (m *Sum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sum.Marshal(b, m, deterministic)
}
func (m *Sum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sum.Merge(m, src)
}
func (m *Sum) XXX_Size() int {
	return xxx_messageInfo_Sum.Size(m)
}
func (m *Sum) XXX_DiscardUnknown() {
	xxx_messageInfo_Sum.DiscardUnknown(m)
}

var xxx_messageInfo_Sum proto.InternalMessageInfo

func (m *Sum) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Sum) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type SumRequest struct {
	Sum                  *Sum     `protobuf:"bytes,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetSum() *Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

type SumResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type NumberPrime struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumberPrime) Reset()         { *m = NumberPrime{} }
func (m *NumberPrime) String() string { return proto.CompactTextString(m) }
func (*NumberPrime) ProtoMessage()    {}
func (*NumberPrime) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *NumberPrime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberPrime.Unmarshal(m, b)
}
func (m *NumberPrime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberPrime.Marshal(b, m, deterministic)
}
func (m *NumberPrime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberPrime.Merge(m, src)
}
func (m *NumberPrime) XXX_Size() int {
	return xxx_messageInfo_NumberPrime.Size(m)
}
func (m *NumberPrime) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberPrime.DiscardUnknown(m)
}

var xxx_messageInfo_NumberPrime proto.InternalMessageInfo

func (m *NumberPrime) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

type PrimeRequest struct {
	Np                   *NumberPrime `protobuf:"bytes,1,opt,name=np,proto3" json:"np,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PrimeRequest) Reset()         { *m = PrimeRequest{} }
func (m *PrimeRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeRequest) ProtoMessage()    {}
func (*PrimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{4}
}

func (m *PrimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeRequest.Unmarshal(m, b)
}
func (m *PrimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeRequest.Marshal(b, m, deterministic)
}
func (m *PrimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeRequest.Merge(m, src)
}
func (m *PrimeRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeRequest.Size(m)
}
func (m *PrimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeRequest proto.InternalMessageInfo

func (m *PrimeRequest) GetNp() *NumberPrime {
	if m != nil {
		return m.Np
	}
	return nil
}

type PrimeResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeResponse) Reset()         { *m = PrimeResponse{} }
func (m *PrimeResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeResponse) ProtoMessage()    {}
func (*PrimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{5}
}

func (m *PrimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeResponse.Unmarshal(m, b)
}
func (m *PrimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeResponse.Marshal(b, m, deterministic)
}
func (m *PrimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeResponse.Merge(m, src)
}
func (m *PrimeResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeResponse.Size(m)
}
func (m *PrimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeResponse proto.InternalMessageInfo

func (m *PrimeResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Sum)(nil), "calculator.Sum")
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*NumberPrime)(nil), "calculator.NumberPrime")
	proto.RegisterType((*PrimeRequest)(nil), "calculator.PrimeRequest")
	proto.RegisterType((*PrimeResponse)(nil), "calculator.PrimeResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x3b, 0x4f, 0xc3, 0x30,
	0x14, 0x85, 0x71, 0x22, 0x75, 0xb8, 0x09, 0x20, 0x79, 0x68, 0x43, 0x59, 0xa8, 0x25, 0xd4, 0x4e,
	0x2d, 0x2a, 0x03, 0xcc, 0x0c, 0x8c, 0x08, 0x25, 0x1b, 0x5b, 0x1c, 0xdd, 0xa1, 0x52, 0x9c, 0x18,
	0x3f, 0x50, 0x7f, 0x05, 0xbf, 0x19, 0xf9, 0x11, 0xd5, 0x3c, 0xc4, 0x96, 0x73, 0x1f, 0xe7, 0xcb,
	0xf1, 0x85, 0x4d, 0xd7, 0xf6, 0x9d, 0xed, 0x5b, 0x33, 0xaa, 0xdd, 0xe9, 0x53, 0xf2, 0x44, 0x6c,
	0xa5, 0x1a, 0xcd, 0x48, 0xe1, 0x54, 0x61, 0x2b, 0xc8, 0x1b, 0x2b, 0x68, 0x09, 0xa4, 0xad, 0xc8,
	0x0d, 0xd9, 0xe4, 0x35, 0x69, 0x9d, 0xe2, 0x55, 0x16, 0x14, 0x67, 0x3b, 0x80, 0xc6, 0x8a, 0x1a,
	0xdf, 0x2d, 0x6a, 0x43, 0x57, 0x90, 0x6b, 0x2b, 0xfc, 0x6c, 0xb1, 0xbf, 0xdc, 0x26, 0xe6, 0x6e,
	0xc8, 0xf5, 0xd8, 0x2d, 0x14, 0x7e, 0x41, 0xcb, 0x71, 0xd0, 0x48, 0xe7, 0x30, 0x53, 0xa8, 0x6d,
	0x6f, 0x22, 0x20, 0x2a, 0x76, 0x0d, 0xc5, 0x8b, 0x15, 0x1c, 0xd5, 0xab, 0x3a, 0x08, 0x74, 0xd0,
	0xe3, 0xf4, 0x0b, 0x47, 0xf6, 0x00, 0xa5, 0x2f, 0x4f, 0xd8, 0x35, 0x64, 0x83, 0x8c, 0xd4, 0x45,
	0x4a, 0x4d, 0x2c, 0xea, 0x6c, 0x90, 0x6c, 0x0d, 0xe7, 0x71, 0xf1, 0x7f, 0xfc, 0xfe, 0x93, 0xf8,
	0x5c, 0x0d, 0xaa, 0x8f, 0x43, 0x87, 0xf4, 0x31, 0x3c, 0xc4, 0xfc, 0x67, 0xa2, 0xc0, 0x5f, 0x2e,
	0x7e, 0xd5, 0x83, 0x3d, 0x3b, 0xa3, 0xcf, 0xdf, 0x73, 0x54, 0xe9, 0x64, 0x9a, 0x61, 0x79, 0xf5,
	0x47, 0x67, 0x72, 0xb9, 0x23, 0x4f, 0x17, 0x6f, 0x65, 0x7a, 0x37, 0x3e, 0xf3, 0xd7, 0xba, 0xff,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0x91, 0x1a, 0x8b, 0x26, 0xd9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SumServiceClient is the client API for SumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumServiceClient interface {
	//Unary API
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	//Server Streaming
	NumberPrime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (SumService_NumberPrimeClient, error)
}

type sumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSumServiceClient(cc grpc.ClientConnInterface) SumServiceClient {
	return &sumServiceClient{cc}
}

func (c *sumServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.SumService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sumServiceClient) NumberPrime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (SumService_NumberPrimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SumService_serviceDesc.Streams[0], "/calculator.SumService/NumberPrime", opts...)
	if err != nil {
		return nil, err
	}
	x := &sumServiceNumberPrimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SumService_NumberPrimeClient interface {
	Recv() (*PrimeResponse, error)
	grpc.ClientStream
}

type sumServiceNumberPrimeClient struct {
	grpc.ClientStream
}

func (x *sumServiceNumberPrimeClient) Recv() (*PrimeResponse, error) {
	m := new(PrimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SumServiceServer is the server API for SumService service.
type SumServiceServer interface {
	//Unary API
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	//Server Streaming
	NumberPrime(*PrimeRequest, SumService_NumberPrimeServer) error
}

// UnimplementedSumServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSumServiceServer struct {
}

func (*UnimplementedSumServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedSumServiceServer) NumberPrime(req *PrimeRequest, srv SumService_NumberPrimeServer) error {
	return status.Errorf(codes.Unimplemented, "method NumberPrime not implemented")
}

func RegisterSumServiceServer(s *grpc.Server, srv SumServiceServer) {
	s.RegisterService(&_SumService_serviceDesc, srv)
}

func _SumService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.SumService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SumService_NumberPrime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SumServiceServer).NumberPrime(m, &sumServiceNumberPrimeServer{stream})
}

type SumService_NumberPrimeServer interface {
	Send(*PrimeResponse) error
	grpc.ServerStream
}

type sumServiceNumberPrimeServer struct {
	grpc.ServerStream
}

func (x *sumServiceNumberPrimeServer) Send(m *PrimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.SumService",
	HandlerType: (*SumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SumService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NumberPrime",
			Handler:       _SumService_NumberPrime_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
